Ignore rescheduled cards in old stats page
ankitects/anki pull request #2863
Opened 2023-12-02 17:03 UTC by user1823

Rescheduled cards are not actual reviews. So, including them in Cards Studied Today is inappropriate.

2023-12-03 04:25 UTC, user1823 commented
I am not sure what's the issue with the last commit. Help would be appreciated.

2023-12-03 09:57 UTC, Gustaf-C commented on pylib/anki/stats.py
> +            lim = "where type != {REVLOG_RESCHED} and " + " and ".join(lims)
These should be f-strings:
```suggestion
            lim = f"where type != {REVLOG_RESCHED} and " + " and ".join(lims)
```

2023-12-03 09:57 UTC, Gustaf-C commented on pylib/anki/stats.py
> +            lim = "where type != {REVLOG_RESCHED}"
```suggestion
            lim = f"where type != {REVLOG_RESCHED}"
```

2023-12-04 10:01 UTC, L-M-Sherlock requested changes

2023-12-04 10:01 UTC, L-M-Sherlock commented on pylib/anki/stats.py
> +            lim = "where type != {REVLOG_RESCHED}"
It should be f"where type != {REVLOG_RESCHED}"

2023-12-04 10:01 UTC, L-M-Sherlock commented on pylib/anki/stats.py
> +            lim = "where type != {REVLOG_RESCHED} and " + " and ".join(lims)
It should be f"where type != {REVLOG_RESCHED} and "

2023-12-04 23:55 UTC, dae commented
Thank you both.

2023-12-04 23:55 UTC, merged