Fix/issue 3659 wrong window closes command w
ankitects/anki pull request #3680
Opened 2024-12-30 03:42 UTC by tampueroc

Fixes #3659
Prevents closing the browser window unless it’s the active window.

2025-01-04 15:16 UTC, abdnh requested changes

2025-01-04 15:16 UTC, abdnh commented on qt/aqt/browser/browser.py
> +        if isinstance(self, AddCards):
`self` can't be AddCards here, so this doesn't make sense.

2025-01-04 15:16 UTC, abdnh commented on qt/aqt/browser/browser.py
> +        if current_window() == self:
Same as above.

2025-01-15 09:26 UTC, dae commented
Closing to reduce clutter; happy to reopen if/when you return to this.

2025-01-15 09:28 UTC, closed without merging