Create a gui_hook for initializing buttons in Models
ankitects/anki pull request #746
Opened 2020-08-23 19:44 UTC by hgiesel

I have two add-ons which create an additional button in the "Models" dialog, one of them being [Asset Manager](https://ankiweb.net/shared/info/656021484).
I found it much better putting an add-ons configuration here over putting it into the Add-ons dialog, when the add-ons configurations are per note type.

2020-08-24 00:15 UTC, dae requested changes
No issues with the hook itself, but some comments below

2020-08-24 00:15 UTC, dae commented on qt/aqt/models.py
> +            ("Options...", self.onAdvanced),
You've broken the translations

2020-08-24 00:15 UTC, dae commented on qt/aqt/models.py
> +            default_buttons[-1:-1] = from_main_buttons
This is difficult to read; I'd prefer you just append or extend() these, and then append Options at the end

2020-08-31 20:38 UTC, hgiesel commented
I don't quite see how I could fix the Ubuntu builds failing? I assume it is a build issue.

2020-08-31 22:35 UTC, dae commented
Looks like an old caching issue, should be good to go. Thanks!

2020-08-31 22:36 UTC, merged